export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  PROGRAMS: '/programs',
  PROGRAM_DETAIL: '/programs/:slug',
  PROJECTS: '/projects',
  PROJECT_DETAIL: '/projects/:slug',
  DONATE: '/donate',
  VOLUNTEER: '/volunteer',
  EVENTS: '/events',
  EVENT_DETAIL: '/events/:slug',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  MEDIA: '/media',
  CONTACT: '/contact',
  FAQ: '/faq',
  PRIVACY: '/privacy-policy',
  TERMS: '/terms',
  CAREERS: '/careers',
  CAREER_DETAIL: '/careers/:slug',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  PORTAL: '/portal',
  PORTAL_PROFILE: '/portal/profile',
  PORTAL_NOTIFICATIONS: '/portal/notifications',
  PORTAL_DONATIONS: '/portal/donations',
  PORTAL_CERTIFICATES: '/portal/certificates',
  PORTAL_DOWNLOADS: '/portal/downloads',
  PORTAL_ACTIVITIES: '/portal/activities',
  ADMIN: '/admin',
  ADMIN_PROGRAMS: '/admin/programs',
  ADMIN_PROJECTS: '/admin/projects',
  ADMIN_EVENTS: '/admin/events',
  ADMIN_NEWS: '/admin/news',
  ADMIN_DONATIONS: '/admin/donations',
  ADMIN_VOLUNTEERS: '/admin/volunteers',
  ADMIN_MEMBERS: '/admin/members',
  ADMIN_CAMPAIGNS: '/admin/campaigns',
  ADMIN_PARTNERS: '/admin/partners',
  ADMIN_TESTIMONIALS: '/admin/testimonials',
  ADMIN_GALLERY: '/admin/gallery',
  ADMIN_CAREERS: '/admin/careers',
  ADMIN_APPLICATIONS: '/admin/applications',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_NEWSLETTER: '/admin/newsletter',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_USERS: '/admin/users',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_MEDIA: '/admin/media',
  ADMIN_ACTIVITY_LOGS: '/admin/activity-logs',
  ADMIN_PROFILE: '/admin/profile',
}

export const API_ENDPOINTS = {
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_REFRESH: '/auth/refresh',
  AUTH_LOGOUT: '/auth/logout',
  AUTH_FORGOT_PASSWORD: '/auth/forgot-password',
  AUTH_RESET_PASSWORD: '/auth/reset-password',
  AUTH_VERIFY_EMAIL: '/auth/verify-email',
  PROGRAMS: '/programs',
  PROJECTS: '/projects',
  EVENTS: '/events',
  NEWS: '/news',
  DONATIONS: '/donations',
  CAMPAIGNS: '/campaigns',
  VOLUNTEERS: '/volunteers',
  GALLERY: '/gallery',
  TESTIMONIALS: '/testimonials',
  PARTNERS: '/partners',
  CAREERS: '/careers',
  APPLICATIONS: '/applications',
  MESSAGES: '/messages',
  NEWSLETTER: '/newsletter',
  USERS: '/users',
  SETTINGS: '/settings',
  REPORTS: '/reports',
  UPLOADS: '/uploads',
}

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  EDITOR: 'editor',
  VOLUNTEER_MANAGER: 'volunteer_manager',
  PROGRAM_MANAGER: 'program_manager',
  FINANCE_OFFICER: 'finance_officer',
  CONTENT_MANAGER: 'content_manager',
  EVENT_MANAGER: 'event_manager',
  DONOR_MANAGER: 'donor_manager',
  VIEWER: 'viewer',
}

export const DONATION_METHODS = {
  ONLINE: 'online',
  BANK_TRANSFER: 'bank_transfer',
  CHECK: 'check',
  CASH: 'cash',
}

export const PROJECT_STATUS = {
  ONGOING: 'ongoing',
  COMPLETED: 'completed',
  UPCOMING: 'upcoming',
}

export const VOLUNTEER_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
}

export const AURORA_COLORS = {
  cyan: '#00E5FF',
  indigo: '#536DFE',
  violet: '#7C4DFF',
  emerald: '#00E676',
  amber: '#FFD740',
  rose: '#FF5252',
}
